RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/ExpectInHook:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/examples/*'
    - 'spec/integration/*'
    - 'spec/system/*'
    - 'spec/e2e/*'

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/SpecFilePathSuffix:
  Exclude:
    - 'spec/README.md'

RSpec/NoExpectationExample:
  Exclude:
    - 'spec/README.md'

RSpec/MultipleDescribes:
  Exclude:
    - 'spec/README.md'

RSpec/RepeatedExampleGroupDescription:
  Exclude:
    - 'spec/README.md'

RSpec/Output:
  Exclude:
    - 'spec/support/**/*'
    - 'spec/config/**/*'
    - 'spec/fixtures/**/*'
