inherit_gem:
  rubocop-lts: config/rubygem_rspec.yml

inherit_from:
  - .rubocop_rspec.yml

plugins: rubocop-on-rbs

AllCops:
  Exclude:
    - certs/**/*
    - checksums/**/*
    - docs/**/*
    - fixtures/**/*
    - gemfiles/*.gemfile
    - pkg/**/*
    - results/**/*
    - spec/fixtures/**/*
    - tmp/**/*
    - vendor/**/*

RBS:
  Enabled: true

Layout/IndentationConsistency:
  Exclude: ['*.md']

ThreadSafety/ClassInstanceVariable:
  Enabled: false

ThreadSafety/NewThread:
  Enabled: false

Layout/TrailingEmptyLines:
  EnforcedStyle: final_blank_line
